#!/bin/bash

# Python virtual environment
echo "Created and activated Python virtual environment";
python3 -m venv ./venv || python -m venv ./venv;
source ./venv/bin/activate;

# Install requirements
npm install;
pip install -r ./requirements.txt;
echo "Installed requirements";

# Compile
tsc -p ./tsconfig.json;
echo "Code compiled successfully";

# Start
echo "Starting GWPC Check-in 2.0";
npm start;