#!/bin/bash

# Install requirements
echo "Installing requirements";
[ ! -d "./node_modules" ] && npm install;
if [ -f "/usr/local/bin/pip3" ]; then
    pip3 install -r ./requirements.txt;
else
    pip install -r ./requirements.txt;
fi
echo "Installed requirements";

# Compile
echo "Compiling TypeScript";
npx tsc -p ./tsconfig.json;
echo "Code compiled successfully";

# Start
echo "Starting GWPC Check-in 2.0";
npm start;