#!/bin/bash

# Install requirements
echo "Installing requirements";
npm install;
pip install -r ./requirements.txt;
echo "Installed requirements";

# Compile
echo "Compiling TypeScript";
npx tsc -p ./tsconfig.json;
echo "Code compiled successfully";

# Start
echo "Starting GWPC Check-in 2.0";
npm start;